
Bloco try/catch serve para tratamento de exceções,
tratamento de códigos que podem não ser totalmente atendidos
e gerarem alguma exceção/erro.

O TRY consegue recuperar erros que possam ocorrer no código fornecido em seu bloco.
O CATCH por sua vez faz o tratamento dos erros que aconteceram.

O bloco FINALLY é utilizado para garantir que um código seja executado após um try

A função do THROW é lançar a exceção para o método chamador, ou seja, leva o erro adiante.

